### ISSUE TITLE
Is there any plan update to use vue-loader 15 and mini-css-extract-plugin?

### ISSUE THREAD

**Issue by ghost** [joaner/vue-webpack4-example#1]
Thanks for the scaffold, Is there any plan update to use vue-loader 15 and mini-css-extract-plugin? thanks very much

**Comment by joaner** [comment]
Thanks for your suggestion, I will research and complete the upgrade in the last two days.

**Comment by joaner** [comment]
Hello buddy, has already used `mini-css-extract-plugin ` instead of `extract-text-webpack-plugin` (see #2). 
But `vue-loader@15.0.0-rc.2` is not an stable version now, so it needs to wait.

**Comment by ghost** [comment]
Thanks :-)
